"""24_miracle adapter — wraps the original external Judge + AI subprocesses
(高翔's run_match.py) and feeds normalized results into the framework's `Run`,
bypassing the framework's `Match`/`BaseRunner` whose win attribution is unsafe
under side-swapping. See docs/games/24_miracle_adapter_status.md."""

from agentbench_frame.games.miracle.result import (
    GameOutcome,
    WIN,
    LOSS,
    DRAW,
    ERROR,
    VALID_RESULTS,
    derive_raw_winner,
    finalize,
    normalize,
    compute_win_rate,
    compute_h2h,
    outcome_counts,
    read_replay_header,
    sha256_file,
    select_games_to_run,
    would_rerun_successful,
    to_event_record,
)
from agentbench_frame.games.miracle.research_protocol import (
    BENCHMARK_VERSION,
    MANIFEST_SCHEMA_VERSION,
    PROTOCOL_VERSION,
    SEED_MAX,
    SEED_MIN,
    TRAJECTORY_KL_EPSILON,
    FROZEN_OPPONENT_DETERMINISM,
    TRAIN_OPPONENTS,
    VALIDATION_OPPONENTS,
    TEST_OPPONENTS,
    FrozenTestCase,
    SeedBundle,
    build_frozen_test_cases,
    canonical_research_manifest_bytes,
    decode_ai_observation,
    enumerate_legal_commands,
    research_protocol_manifest,
    research_manifest_sha256,
)
from agentbench_frame.games.miracle.iteration_protocol import (
    BOOTSTRAP_TEMPLATE_VERSION,
    APPROVED_BOOTSTRAP_SHA256,
    APPROVED_HUMAN_REPLAY_SKILL_SHA256,
    APPROVED_MATCH_PLAN_MANIFEST_SHA256,
    APPROVED_REPLAY_EVIDENCE_MANIFEST_SHA256,
    APPROVED_CANDIDATE_EVALUATION_PLAN_SHA256,
    APPROVED_EVALUATION_EVIDENCE_MANIFEST_SHA256,
    APPROVED_ITERATION_ACCEPTANCE_MANIFEST_SHA256,
    CURRENT_APPROVED_HUMAN_CHAMPION_SHA256,
    EXPERIENCE_SKILL_SCHEMA_VERSION,
    HUMAN_REPLAY_SKILL_SCHEMA_VERSION,
    ITERATION_PROTOCOL_VERSION,
    MATCH_PLAN_SCHEMA_VERSION,
    REPLAY_EVIDENCE_SCHEMA_VERSION,
    CANDIDATE_EVALUATION_PLAN_SCHEMA_VERSION,
    EVALUATION_EVIDENCE_SCHEMA_VERSION,
    ITERATION_ACCEPTANCE_SCHEMA_VERSION,
    HUMAN_AUTHORED_CONTENT_REQUIRED,
    LEGAL_ACTION_UNIT,
    BootstrapTemplate,
    BaselineStoredContext,
    AcceptanceConfig,
    CandidateEvaluationPlan,
    CandidateStoredContext,
    CapturedReplay,
    ChangeOperation,
    ChangePlan,
    ComplexityMetrics,
    HumanChampion,
    HumanReplaySkill,
    ImmutableIterationStore,
    IterationOutcome,
    IterationPreflightError,
    IterationAcceptanceManifest,
    EvaluationCaseEvidence,
    EvaluationConfig,
    EvaluationEvidenceManifest,
    EvaluationPlanCase,
    EvaluationReadyContext,
    LearningConfig,
    LearningReadyContext,
    LifecycleState,
    MatchConfig,
    MatchPlanCase,
    MatchPlanManifest,
    MatchReadyContext,
    MiracleExperienceSkill,
    ReplayApprovedContext,
    ReplayEvidenceManifest,
    StrategyVersion,
    bootstrap_strategy_source_sha256,
    build_replay_evidence_manifest,
    canonical_iteration_protocol_manifest_bytes,
    compute_complexity_metrics,
    default_bootstrap_template,
    derive_iteration_outcome,
    iteration_protocol_manifest,
    materialize_bootstrap_strategy,
    materialize_empty_experience,
    open_learning_after_preflight,
    open_match_after_preflight,
    open_evaluation_after_preflight,
    preflight_baseline_stored,
    preflight_candidate_stored,
    preflight_evaluation,
    preflight_iteration,
    preflight_learning,
    preflight_match,
    preflight_replay,
    validate_bootstrap_template,
)
from agentbench_frame.games.miracle.decision_kl_v1 import (
    DecisionKLEvidence,
    DecisionKLRecord,
    TrajectoryKLSummary,
    build_trusted_action_support,
    compute_trajectory_kl,
    trusted_support_identity,
    validate_distribution,
)
from agentbench_frame.games.miracle.replay_reading_v1 import (
    DecisionFrame,
    ReplayPacket,
    ReplayReadingContext,
    open_replay_reading,
    preflight_replay_reading,
    render_replay_timeline,
)
from agentbench_frame.games.miracle.ifelse_policy_state_v1 import (
    ExplicitIfElseStateMachineV1,
    IncompletePolicyEvidenceError,
    LegacyPolicySourceV1,
    PolicyComparisonIdentityV1,
    PolicyConfigV1,
    PolicyMemoryV1,
    PolicyPairDecisionV1,
    ProviderIdentityV1,
    SequentialReplayAuditV1,
    audit_sequential_trace,
)

__all__ = [
    "GameOutcome", "WIN", "LOSS", "DRAW", "ERROR", "VALID_RESULTS",
    "derive_raw_winner", "finalize", "normalize", "compute_win_rate",
    "compute_h2h", "outcome_counts", "read_replay_header", "sha256_file",
    "select_games_to_run", "would_rerun_successful", "to_event_record",
    "BENCHMARK_VERSION", "MANIFEST_SCHEMA_VERSION", "PROTOCOL_VERSION",
    "SEED_MIN", "SEED_MAX", "TRAJECTORY_KL_EPSILON", "TRAIN_OPPONENTS", "VALIDATION_OPPONENTS",
    "TEST_OPPONENTS", "FROZEN_OPPONENT_DETERMINISM", "FrozenTestCase", "SeedBundle",
    "build_frozen_test_cases", "canonical_research_manifest_bytes",
    "decode_ai_observation", "enumerate_legal_commands",
    "research_protocol_manifest", "research_manifest_sha256",
    "BOOTSTRAP_TEMPLATE_VERSION", "APPROVED_BOOTSTRAP_SHA256",
    "APPROVED_HUMAN_REPLAY_SKILL_SHA256", "APPROVED_MATCH_PLAN_MANIFEST_SHA256",
    "APPROVED_REPLAY_EVIDENCE_MANIFEST_SHA256",
    "APPROVED_CANDIDATE_EVALUATION_PLAN_SHA256",
    "APPROVED_EVALUATION_EVIDENCE_MANIFEST_SHA256",
    "APPROVED_ITERATION_ACCEPTANCE_MANIFEST_SHA256",
    "CURRENT_APPROVED_HUMAN_CHAMPION_SHA256", "EXPERIENCE_SKILL_SCHEMA_VERSION",
    "HUMAN_REPLAY_SKILL_SCHEMA_VERSION", "MATCH_PLAN_SCHEMA_VERSION",
    "REPLAY_EVIDENCE_SCHEMA_VERSION",
    "CANDIDATE_EVALUATION_PLAN_SCHEMA_VERSION", "EVALUATION_EVIDENCE_SCHEMA_VERSION",
    "ITERATION_ACCEPTANCE_SCHEMA_VERSION",
    "ITERATION_PROTOCOL_VERSION", "HUMAN_AUTHORED_CONTENT_REQUIRED",
    "LEGAL_ACTION_UNIT", "BootstrapTemplate", "BaselineStoredContext", "AcceptanceConfig",
    "CandidateEvaluationPlan", "CandidateStoredContext", "CapturedReplay",
    "ChangeOperation", "ChangePlan", "ComplexityMetrics", "HumanChampion",
    "HumanReplaySkill", "ImmutableIterationStore", "IterationOutcome",
    "IterationPreflightError", "IterationAcceptanceManifest", "EvaluationCaseEvidence",
    "EvaluationConfig", "EvaluationEvidenceManifest", "EvaluationPlanCase", "EvaluationReadyContext",
    "LearningConfig", "LearningReadyContext", "LifecycleState",
    "MatchConfig", "MatchPlanCase", "MatchPlanManifest", "MatchReadyContext",
    "MiracleExperienceSkill", "ReplayApprovedContext", "ReplayEvidenceManifest",
    "StrategyVersion", "canonical_iteration_protocol_manifest_bytes",
    "bootstrap_strategy_source_sha256", "build_replay_evidence_manifest",
    "compute_complexity_metrics", "default_bootstrap_template", "derive_iteration_outcome",
    "iteration_protocol_manifest", "materialize_bootstrap_strategy", "materialize_empty_experience",
    "open_learning_after_preflight", "open_match_after_preflight", "open_evaluation_after_preflight",
    "preflight_baseline_stored", "preflight_candidate_stored",
    "preflight_evaluation", "preflight_iteration", "preflight_learning", "preflight_match",
    "preflight_replay", "validate_bootstrap_template",
    "DecisionKLEvidence", "DecisionKLRecord", "TrajectoryKLSummary", "build_trusted_action_support",
    "compute_trajectory_kl", "trusted_support_identity",
    "validate_distribution",
    "DecisionFrame", "ReplayPacket", "ReplayReadingContext",
    "open_replay_reading", "preflight_replay_reading", "render_replay_timeline",
    "ExplicitIfElseStateMachineV1", "IncompletePolicyEvidenceError",
    "LegacyPolicySourceV1", "PolicyComparisonIdentityV1", "PolicyConfigV1",
    "PolicyMemoryV1", "PolicyPairDecisionV1", "ProviderIdentityV1",
    "SequentialReplayAuditV1", "audit_sequential_trace",
]
