"""Isolated adapter for the external 24_miracle Judge runtime.

The package wraps subprocess/runtime behavior and normalizes results without
reimplementing Judge rules in process.
"""

from agentbench_frame.games.miracle.result import (
    DRAW,
    ERROR,
    LOSS,
    VALID_RESULTS,
    WIN,
    GameOutcome,
    compute_h2h,
    compute_win_rate,
    derive_raw_winner,
    finalize,
    normalize,
    outcome_counts,
    read_replay_header,
    select_games_to_run,
    sha256_file,
    to_event_record,
    would_rerun_successful,
)
from agentbench_frame.games.miracle.research_protocol import (
    BENCHMARK_VERSION,
    FROZEN_OPPONENT_DETERMINISM,
    MANIFEST_SCHEMA_VERSION,
    PROTOCOL_VERSION,
    SEED_MAX,
    SEED_MIN,
    TEST_OPPONENTS,
    TRAJECTORY_KL_EPSILON,
    TRAIN_OPPONENTS,
    VALIDATION_OPPONENTS,
    FrozenTestCase,
    SeedBundle,
    build_frozen_test_cases,
    canonical_research_manifest_bytes,
    decode_ai_observation,
    enumerate_legal_commands,
    research_manifest_sha256,
    research_protocol_manifest,
)

__all__ = [
    "GameOutcome",
    "WIN",
    "LOSS",
    "DRAW",
    "ERROR",
    "VALID_RESULTS",
    "derive_raw_winner",
    "finalize",
    "normalize",
    "compute_win_rate",
    "compute_h2h",
    "outcome_counts",
    "read_replay_header",
    "sha256_file",
    "select_games_to_run",
    "would_rerun_successful",
    "to_event_record",
    "BENCHMARK_VERSION",
    "MANIFEST_SCHEMA_VERSION",
    "PROTOCOL_VERSION",
    "SEED_MIN",
    "SEED_MAX",
    "TRAJECTORY_KL_EPSILON",
    "TRAIN_OPPONENTS",
    "VALIDATION_OPPONENTS",
    "TEST_OPPONENTS",
    "FROZEN_OPPONENT_DETERMINISM",
    "FrozenTestCase",
    "SeedBundle",
    "build_frozen_test_cases",
    "canonical_research_manifest_bytes",
    "decode_ai_observation",
    "enumerate_legal_commands",
    "research_protocol_manifest",
    "research_manifest_sha256",
]
